# Generated by Django 2.2.3 on 2020-11-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='localtion',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
