# Generated by Django 2.2.5 on 2020-11-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_user_isadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('timestamp', models.IntegerField()),
                ('post_id', models.IntegerField()),
            ],
        ),
    ]
