# Generated by Django 2.2.5 on 2020-11-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
