# Generated by Django 2.2.3 on 2020-11-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='emailVerifyState',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
