# Generated by Django 2.2.3 on 2020-11-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_member_emailverifystate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='emailVerifyCode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
