# Generated by Django 3.1.3 on 2020-11-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_member_emailverifycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=30)),
                ('emailVerifyState', models.CharField(default='null', max_length=10)),
                ('emailVerifyCode', models.CharField(default='', max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='emailVerifyCode',
        ),
        migrations.RemoveField(
            model_name='member',
            name='emailVerifyState',
        ),
    ]
